//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cust_enrty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class allocate
    {
        public int allocate_id { get; set; }
        public Nullable<int> amin_id { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<int> fee_id { get; set; }
        public string Date { get; set; }
        public Nullable<int> paid_id { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual allocate allocate1 { get; set; }
        public virtual allocate allocate2 { get; set; }
        public virtual charges_info charges_info { get; set; }
        public virtual customer_info customer_info { get; set; }
        public virtual paid paid { get; set; }
    }
}
