//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cust_enrty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer_info()
        {
            this.allocates = new HashSet<allocate>();
        }
    
        public int cust_id { get; set; }
        public string name { get; set; }
        public string father_name { get; set; }
        public string email { get; set; }
        public string cnic { get; set; }
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<allocate> allocates { get; set; }
    }
}
