//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cust_enrty.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cust_indicationEntities1 : DbContext
    {
        public cust_indicationEntities1()
            : base("name=cust_indicationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<allocate> allocates { get; set; }
        public virtual DbSet<charges_info> charges_info { get; set; }
        public virtual DbSet<customer_info> customer_info { get; set; }
        public virtual DbSet<paid> paids { get; set; }
    }
}
